import FormTextArea from './FormTextArea'
import FormTextInput from './FormInput'
import FormSelect from './FormSelect'
import CheckBoxFom from './CheckboxForm'
import SliderForm from './SliderForm'
import { FormSwitch } from './FormSwitch'
import { FormColorPicker } from './FormColorPicker'
import { FormTimePicker } from './FormTimePicker'
import { FormOtpInput } from './FormOtpInput'
export { FormTextArea, FormTextInput, FormSelect, CheckBoxFom, SliderForm, FormSwitch, FormColorPicker, FormTimePicker, FormOtpInput }
