export enum CARS_KEYS {
  ALL_CARS = 'ALL_CARS',
  ADD_CAR = 'ADD_CAR',
  UPDATE_CAR = 'UPDATE_CAR',
  DELETE_CAR = 'DELETE_CAR',
  DELETE_ALL_CARS = 'DELETE_ALL_CARS',
  ALL_CARS_CATEGORIES = 'ALL_CARS_CATEGORIES',
  ALL_CARS_EQUIPMENTS = 'ALL_CARS_EQUIPMENTS',
}
