export enum USERS_KEYS {
  WHO_AMI = 'WHO_AMI',
  UPDATE_USER = 'UPDATE_USER',
  DEACTIVATE_ACCOUNT = 'DEACTIVATE_ACCOUNT',
  ACTIVATE_ACCOUNT = 'ACTIVATE_ACCOUNT',
  CLEAR_ALL_SESSIONS = 'CLEAR_ALL_SESSIONS',
  CREATE_PASSKEY = 'CREATE_PASSKEY',
  REVOKE_PASSKEY = 'REVOKE_PASSKEY',
  SESSIONS = 'SESSIONS',
  REVOKE_SESSION = 'REVOKE_SESSION',
  CREDENTIAL_LIST = 'CREDENTIAL_LIST',
}
